data_table_5:
  description: "My new data table"
  columns:
  - column_index: 0
    original_column: userid
    column_type: STRING
  - column_index: 1
    original_column: hostname
    column_type: STRING