cisco_umbrella_top_1k_domains:
  description: Cisco Umbrella top 1,000 domains
  columns:
  - column_index: 0
    original_column: rank
    column_type: STRING
  - column_index: 1
    original_column: domain
    column_type: STRING